### ISSUE TITLE
Error due to undeclared variables

### ISSUE THREAD

**Issue by ghost** [NIEjx/ehentai-Image#1]
Just comment on line 42 and everything works correctly.

> 图片数： 233
Start to get imgURL
Traceback (most recent call last):
  File "pyImgEH.py", line 181, in <module>
    main()
  File "pyImgEH.py", line 171, in main
    all_imgs = getImgAddr(int(tmp))
  File "pyImgEH.py", line 42, in getImgAddr
    id = j + i
NameError: name 'j' is not defined

Dont download file from page 0.  I have to add  
> addrlist.append(url)

in line 25. getImgAddr() function.

BTW, you also need to install lxml. 
`pip3 install lxml`

**Comment by A6Hdz** [comment]
> Just comment on line 42 and everything works correctly.
> 
> > 图片数： 233
> > Start to get imgURL
> > Traceback (most recent call last):
> > File "pyImgEH.py", line 181, in 
> > main()
> > File "pyImgEH.py", line 171, in main
> > all_imgs = getImgAddr(int(tmp))
> > File "pyImgEH.py", line 42, in getImgAddr
> > id = j + i
> > NameError: name 'j' is not defined
> 
> Dont download file from page 0. I have to add
> 
> > addrlist.append(url)
> 
> in line 25. getImgAddr() function.
> 
> BTW, you also need to install lxml.
> `pip3 install lxml`
